In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('sleep.csv')
type(df)

pandas.core.frame.DataFrame

In [22]:
sleep = df["TotalSleepTime"] >= 8*60
print(sleep)
count = sleep.sum()
print(count)
#number of people with more than 8 hours of sleep, 29
#print(type(sleep))
#print(type(df["TotalSleepTime"]))

0      False
1      False
2      False
3      False
4      False
       ...
629    False
630    False
631    False
632    False
633    False
Name: TotalSleepTime, Length: 634, dtype: bool
29

In [23]:
mean_gpa = df[sleep]["cum_gpa"].mean()
median_gpa = df[sleep]["cum_gpa"].median()
std_gpa = df[sleep]["cum_gpa"].std()
print(mean_gpa)
print(median_gpa)
print(std_gpa)

3.5089824351724133
3.5333330000000003
0.3378124871859502

In [24]:
sleepLess = df["TotalSleepTime"] < 8*60
print(sleepLess)
countLess = sleepLess.sum()
print(countLess)
mean_gpaLess = df[sleepLess]["cum_gpa"].mean()
print("This is mean gpa of people who sleep less time 8 hours", mean_gpaLess)
#people who sleep more than 8 hours have higher GPA

0      True
1      True
2      True
3      True
4      True
       ...
629    True
630    True
631    True
632    True
633    True
Name: TotalSleepTime, Length: 634, dtype: bool
605
This is mean gpa of people who sleep less time 8 hours 3.4635164466661155

In [25]:
adjustedGPA = df.loc[df["subject_id"] == 180, "cum_gpa"] = 1.25
print(adjustedGPA)
mean_gpa = df[sleep]["cum_gpa"].mean()
median_gpa = df[sleep]["cum_gpa"].median()
std_gpa = df[sleep]["cum_gpa"].std()
print(mean_gpa)
print(median_gpa)
print(std_gpa)

1.25
3.4317410558620685
3.5333330000000003
0.5386790842250294

In [29]:
sleep = pd.read_csv("shared/data/sleep.csv")
sleep.head(5)
print(sleep.columns)

Index(['subject_id', 'study', 'cohort', 'demo_race', 'demo_gender',
       'demo_firstgen', 'bedtime_mssd', 'TotalSleepTime', 'midpoint_sleep',
       'frac_nights_with_data', 'daytime_sleep', 'cum_gpa', 'term_gpa',
       'term_units', 'Zterm_units_ZofZ'],
      dtype='object')

In [32]:
cd = sleep[(sleep['frac_nights_with_data'] == 1.0) & (sleep["cum_gpa"] > 3.0)]
type((sleep["cum_gpa"] > 3.0))
cd

,subject_id,study,cohort,demo_race,demo_gender,demo_firstgen,bedtime_mssd,TotalSleepTime,midpoint_sleep,frac_nights_with_data,daytime_sleep,cum_gpa,term_gpa,term_units,Zterm_units_ZofZ
1,158,5,lac1,0,1,0,0.141681,391.931035,364.465517,1.0,13.137931,3.660000,2.600000,64,2.482534122
3,102,5,lac1,0,1,1,0.130148,392.620690,416.482759,1.0,54.551724,3.610000,3.560000,61,1.958280544
9,137,5,lac1,1,1,0,0.085000,308.965517,334.793103,1.0,85.482759,3.530000,2.550000,59,1.608778158
10,279,5,lac1,1,1,0,0.168518,314.586207,479.362069,1.0,21.413793,3.610000,3.490000,59,1.608778158
12,337,5,lac1,1,1,0,0.089356,389.724138,447.862069,1.0,14.551724,3.330000,3.740000,58,1.434026965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,92412,4,nh,1,0,0,0.044740,443.700000,338.550000,1.0,54.866667,4.000000,4.000000,,
618,93485,4,nh,1,0,0,0.061560,419.266667,328.433333,1.0,19.766667,3.888833,3.666667,,
621,95543,4,nh,0,0,0,0.063219,363.200000,438.366667,1.0,17.600000,3.833500,3.944500,,
622,95559,4,nh,1,0,0,0.103360,351.500000,394.533333,1.0,65.466667,3.111167,3.166833,,
633,84390,4,nh,1,1,,0.132108,327.666667,476.833333,1.0,42.000000,3.277833,3.222167,,